site_name: GLOBALISE Docs
repo_name: "globalise-huygens/docs.globalise.huygens.knaw.nl/"
repo_url: "https://github.com/globalise-huygens/docs.globalise.huygens.knaw.nl/"

theme:
  name: material
  # logo: static/img/logo/globalise_g.svg
  favicon: static/img/logo/globalise_g.svg
  #icon:
  #  logo: material/flask
  features:
    # - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.top

nav:
  - Home: index.md
  #- About: about.md
  - "GLOBALISE Guiding Principles":
      - "Mission and Research Themes": mission/mission_researchthemes.md
      - "Guiding Key Research Questions": mission/themes-questions.md
  - "GLOBALISE Ethics Guidelines":
      - "Ethics Policy": ethics/policy.md
      - "Ethical Review of Work Processes": ethics/workflow-review.md
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.details
  - footnotes
plugins:
  - search # necessary for search to work
  - git-revision-date-localized
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: material/web
      name: Website
      link: https://globalise.huygens.knaw.nl/
  generator: false
copyright: <p>
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License"
  style="border-width:0" src="https://licensebuttons.net/i/l/by-sa/transparent/ff/ff/ff/88x31.png" /></a><br/>
  <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">GLOBALISE Docs</span> provides background documentation to <a
  xmlns:cc="http://creativecommons.org/ns#" href="https://globalise.huygens.knaw.nl/" property="cc:attributionName"
  rel="cc:attributionURL">GLOBALISE</a>, a project based at the <a href="https://www.huygens.knaw.nl/">Huygens Institute</a> in Amsterdam and funded by GLOBALISE is funded by the <a href="https://www.nwo.nl/en">The Netherlands Organization for Scientific Research (NWO)</a>.
  <br>
  Information on this static website is licensed under a <a rel="license"
  href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons BY-SA 4.0 International License</a>.
  </p>
